### ISSUE TITLE
Markdown issues

### ISSUE THREAD

**Issue by timbrisc** [loinc/loinc-fhir-codesystem#3]
@JohnLHook I just noticed some formatting issues in ReleaseNotes.md that aren't getting rendered properly. Also, it's a pet peeve of mine to not use dashes in a YYYY-MM-DD date. I'll fix if that's OK.

**Comment by JohnLHook** [comment]
Yes. Please fix. I just followed the existing date format that was in the file

From: Tim Briscoe ***@***.***>
Sent: Friday, March 26, 2021 2:12 PM
To: loinc/loinc-fhir-codesystem ***@***.***>
Cc: Hook, John ***@***.***>; Mention ***@***.***>
Subject: [External] [loinc/loinc-fhir-codesystem] Markdown issues (#3)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


@JohnLHook<https://github.com/JohnLHook> I just noticed some formatting issues in ReleaseNotes.md that aren't getting rendered properly. Also, it's a pet peeve of mine to not use dashes in a YYYY-MM-DD date. I'll fix if that's OK.
